# which general environment to run in
Universe = vanilla
# Universe = docker
# docker_image = kreczko/workernode6:latest
# which command to call
executable = myscript.sh
# arguments to the command
#args = /etc/redhat-release

getenv = True
#+SingularityImage = "/cvmfs/singularity.opensciencegrid.org/kreczko/workernode:centos6"
# or
#+SingularityImage = "/cvmfs/singularity.opensciencegrid.org/bbockelm/cms:rhel7"
+SingularityImage = "/cvmfs/singularity.opensciencegrid.org/kreczko/workernode:centos7"
# for CentOS 7

# output files (per job) - the slashes are only needed for the cat command
output = simple/job.$(cluster).$(process).out
error = simple/job.$(cluster).$(process).err
log = simple/job.log
# should files be transfered
should_transfer_files = YES
when_to_transfer_output = ON_EXIT_OR_EVICT

# resource requirements
# number of CPUs
request_cpus = 1
# RAM in MB
request_memory=10
# DISK in KB
request_disk=100

requirements = TARGET.Machine=="hd60.dice.priv"
#requirements = TARGET.Machine=="sm23.hadoop.cluster"

#+WantJobRouter = True
+MAGIC=true
getenv = True
#
# Tell HTCondor to run 3 instances of our job
#
queue 1
